config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/login', to: 'sessions#destroy'
  resources :users
  resources :groups
  resources :photos
  resources :avatars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blob.rb
class Blob
    attr_reader :id, :data
    class << self
      def create(data)
        id = SecureRandom.hex 32
        File.open('/photos/' + id, 'wb') do |file|
          file.write(data)
        end
        Blob.new id, data
      end
  
      def load(id)
        data = nil
        File.open('/photos/' + id, 'rb') do |file|
          data = file.read()
        end
        return nil unless data
        Blob.new id, data
      end
    end
  
    def initialize(id, data = nil)
      @id = id
      @data = data
    end
  end
  

app/models/group.rb
class Group < ApplicationRecord
end

app/models/photo.rb
require 'mini_magick'
MiniMagick.configure do |config|
  config.cli = :graphicsmagick
  config.timeout = 5
end

def sanitize(data)
  name_in = './tmp/' + SecureRandom.hex
  name_out = './tmp/' + SecureRandom.hex + '.jpeg'
  file_in = File.new name_in, 'wb'
  file_in.write data
  file_in.close

  image = MiniMagick::Image.open(name_in)
  image.auto_orient
  image.format 'jpeg'
  image.strip
  image.write name_out

  file_out = File.open name_out, 'rb'
  transformed = file_out.read
  file_out.close
  File.unlink name_in
  File.unlink name_out
  transformed
end

def crop_avatar(data, x, y, width, height, rotation)
  name_in = './tmp/' + SecureRandom.hex
  name_out = './tmp/' + SecureRandom.hex + '.jpeg'
  file_in = File.new name_in, 'wb'
  file_in.write data
  file_in.close

  image = MiniMagick::Image.open(name_in)
  image.crop "#{width}x#{height}+#{x}+#{y}"
  image.rotate rotation
  image.resize '200x200'
  image.write name_out

  file_out = File.open name_out, 'rb'
  transformed = file_out.read
  file_out.close
  File.unlink name_in
  File.unlink name_out
  transformed
end

class Photo < ApplicationRecord
  belongs_to :user
  has_one :post

  def upload(data)
    original_blob = Blob.create data
    data = sanitize data
    fullsize_blob = Blob.create data

    self.original = original_blob.id
    self.fullsize = fullsize_blob.id
    save
  end

  def create_avatar(params)
    data = fullsize_blob
    avatar_data = crop_avatar data, params[:x], params[:y], params[:width],
                       params[:height], params[:rotation]
    avatar_blob = Blob.create avatar_data
    self.avatar = avatar_blob.id
    user.avatar = avatar_blob.id
    save
  end

  def fullsize_blob
    Blob.load(fullsize).data
  end

  def avatar_blob
    Blob.load(avatar).data
  end
end

app/models/session.rb
class Session
  include ActiveModel::Model

  attr_accessor :username, :password, :user

  validates :username, presence: true
  validates :password, presence: true

  def self.authenticate(params)
    session = Session.new params
    session.valid? && session.authenticate
    session
  end

  def authenticate
    user = User.find_by(username: username.downcase)
    unless user
      errors.add :username, 'doesn\'t exist'
      return
    end
    unless user.authenticate password
      errors.add :password, 'is wrong'
      return
    end
    @user = user
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  validates :name, length: { in: 2..128 }, if: -> { name.present? }
  validates :username, presence: true, length: {in: 4..64},
    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 8 }, if: -> { password.present? }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
    def edit
        render :edit, :layout => false 
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    before_action :logged_in_user
    def new
        @group = Group.new
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :logged_in_user
    def index
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    before_action :logged_in_user

    def create
        @photo = current_user.photos.create photo_params
        render json: { id: @photo.id }
    end

    def update
        photo = current_user.photos.find(params[:id])
        photo.upload(request.body.read)
    end

    def show
        # todo: fixme: authorization
        photo = Photo.find(params[:id])
        send_data photo.fullsize_blob, type: 'image/jpeg'
    end

    private
    def photo_params
        params.permit(:mimetype, :name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_session, only: [:show, :edit, :update, :destroy]
  # GET /sessions/new
  def new
    @session = Session.new
  end

  # POST /sessions
  # POST /sessions.json
  def create
    @session = Session.authenticate session_params

    respond_to do |format|
      if @session.user.nil?
        format.js { render :new, status: 403 }
        format.html { render :new }
      else
        log_in @session.user
        format.html { redirect_to :root }
      end
    end
  end

  private

  def session_params
    params.permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to :root, notice: 'User was successfully created.' }
        format.json { redirect_to :root, status: :created, location: @user }
      else
        format.js { render :new }
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    respond_to do |format|
      format.js { render :new }
      format.json { render json: ['stavros', 'nikos'] }
    end
  end

  def show
    respond_to do |format|
      format.js { render :new }
      format.json { render json: [{name: params['q'], id: 1}, {name: 'stavros', id: 2}, {name: 'nikos', id: 3}] }
    end
  end

  def edit
    @user = current_user
  end

  private
    def user_params
      params.require(:user).permit(:name, :username, :password, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
# SesisonHelper
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def logged_in_user
    return if logged_in?

    flash[:danger] = 'Please log in'
    redirect_to login_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/avatars/edit.html.erb
<div class="modal-background"></div>
<div class="modal-content box">
    <div style="{styles.avatarDiv}">
        <img class="image" src="https://media.istockphoto.com/photos/bikes-at-googleplex-google-headquarters-picture-id675079800?s=2048x2048">
        <div style="{styles.avatarEditButtons}" >
            <input type="range" min="1" max="{this.state.maxZoom}" step="0.01" value="{this.state.scale}" >
            <span class="icon-button">
                <i class="fas fa-undo-alt"></i>
            </span>
            <span class="icon-button" >
                <i class="fas fa-redo-alt"></i>
            </span>
        </div>
        <div style="{styles.avatarActionButtons}">
            <button class="primary">Apply</button>
            <button>Cancel</button>
        </div>
    </div>
</div>

app/views/groups/_form.html.erb
<%= form_with(url: groups_path, id: 'groups-new-form') do |form| %>

    <div class="form-group">
        <label>Name</label>
        <%= form.text_field :subject, value: @group.subject  %>
        <% unless @group.errors[:subject].empty? %>
            <div class="input-error">Name <%= @group.errors[:subject][0] %></div>
        <% end %>
    </div>

    <div class="form-group">
        <label>Members</label>
        <div class="select-wrap" style="position: relative;">
            <input type="text" class="select-input" style="width: 100%;">
            <div class="select-dropdown" style="display: none;">
                <div class="select-item">Stavros</div>
            </div>
        </div>
    </div>
    
    <div class="form-group">
        <%= form.submit 'Create', class: 'primary' %>
    </div>
<% end %>

app/views/groups/new.html.erb
<div class="content">
    <div class="main">
        <div class="content">
            <div class="left">
            </div>
            <div class="center">
                <div class="box">
                    <div class="box-header">Create a new group</div>
                    <%= render "form" %>
                </div>
            </div>
            <div class="right">
            </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card" style="min-height: 600px; padding: 0">
                <div style="fontSize: 18; fontWeight: 200; text-align: center; margin: 12px">
                    Groups
                </div>
                <div style="display: flex; flex-direction: column; margin: 12px">
                    <button class="btn btn-primary" onClick="{this.onClickCreateGroup.bind(this)}">Create</button>
                </div>
                <div style="margin: 24px 0">
                    <%# {this.state.groups.map(g => (
                        <Link to={`/groups/${g.id}`} component="div" key={g.id} style={styles.groupButtonStyles[g.id == groupId ? 'active' : 'inactive']}>
                            {g.name}
                        </Link>
                    ))} %>
                </div>
            </div>
        </div>
        <div class="col-7">
            <%# {center} %>
            <div class="card">
                <div class="card-body">
                    <%= link_to "New Group", new_group_path %>
                    <%= link_to "Edit Profile", edit_user_path(current_user) %>
                </div>
            </div>
        </div>
        <div class="col">
        </div>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
  <div class="container">
    <a class="navbar-brand" href="/">Rinthine</a>
    <% if logged_in? %>
      <div class="navbar-nav mr-auto">
        <%# <a class="nav-item nav-link" href="/">
          <span class="icon"><i class="fas fa-rss"></i></span>
          <span>Feed</span>
        </a>
        <a class="nav-item nav-link" href="/connections">
          <span class="icon"><i class="fas fa-exchange-alt"></i></span>
          <span>Connections</span>
        </a> %>
      </div>
      <ul class="navbar-nav my-2 my-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" href="">@Stavros</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="/profile">Profile </a>
            <a class="dropdown-item" href="/logout">Logout</a>
          </div>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rinthine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <div style="margin-top: 12px">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: @user, url: :signup, id: 'users-new-form') do |form| %>

  <div class="form-group">
     <%= form.label :username do %>
      Choose a username<span class="required">*</span>
    <% end %>
    <%= form.text_field :username, value: @user.username, class: 'form-control' %>
    <% unless @user.errors[:username].empty? %>
      <small class="form-text text-danger">Username <%= @user.errors[:username][0] %></small>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :password do %>
      Choose a password<span class="required">*</span>
    <% end %>
    <%= form.password_field :password, class: 'form-control' %>
    <% unless @user.errors[:password].empty? %>
      <small class="form-text text-danger">Password <%= @user.errors[:password][0] %></small>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :email do %>
      Enter you email <small>(optional)</small>
    <% end %>
    <%= form.text_field :email, value: @user.email, class: 'form-control' %>
    <% unless @user.errors[:email].empty? %>
      <small class="form-text text-danger">Email <%= @user.errors[:email][0] %></small>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.submit 'Register', data: { "disable-with": "Register" }, class: 'btn btn-primary' %>
    <div>
      <small>Already have an account? <a class="link" href="/login">Login!</a></small>
    </div>
  </div>
<% end %>

app/views/users/_profile.html.erb
<%= form_with(model: @user, url: :signup, id: 'users-new-form') do |form| %>
    <div class="form-group">
        <%= form.label "Username" %>
        <input type="text" name="username" >
        <div class="input-error">"{this.state.errors.username}"</div>
    </div>
    <div class="form-group">
        <label>Name</label>
        <input type="text" name="name">
        <div class="input-error">"{this.state.errors.name}"</div>
    </div>
    <div class="form-group">
        <label>Email</label>
        <input type="email" name="email" >
        <div class="input-error">"{this.state.errors.email}"</div>
    </div>
    <div class="form-group">
        <button class="{`primary${this.state.submitting ? ' loading' : ''}`}">Update</button>
        <div class="input-error">"{this.state.errors.other}"</div>
    </div>
<% end %>

app/views/users/edit.html.erb
<div class="content">
    <div class="left"></div>
    <div class="center">
        <div class="box">
            <div class="box-header">Profile</div>
            <div style="{styles.headerSection}">
                <div style="{styles.photo}">
                    <div class="post-image" style="{styles.image}">
                        <img src="/photos/102">
                    </div>
                    <form>
                        <div class="form-group uploader-wrap">
                            <input class="file uploader-input" type="file" id="file">
                            <label class="button for-file uploader-button" for="file">
                                <span>Update photo</span>
                            </label>
                        </div>
                    </form>
                </div>
            </div>
            <%= render 'profile' %>
        </div>
    </div>
    <div class="right"></div>
</div>

app/views/users/new.html.erb
<div class="container">
    <div class="row">
        <div class="col">
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Signup</h3>
                    <%= render "form" %>
                </div>
            </div>
        </div>
        <div class="col">
        </div>
    </div>
</div>

app/views/users/new.js.erb
$('#users-new-form').replaceWith('<%= j render "form" %>');